development:
  adapter: postgresql
  database: websockets-sample_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: websockets-sample_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: websockets-sample_production
  pool: 5
  timeout: 5000
